version: '3'

services:
    api:
      image: ${API_IMAGE}
      container_name: prosimos-api
      expose:
        - "5000"
      ports:
        - "5000:5000"

    client:
      image: ${CLIENT_IMAGE}
      container_name: prosimos-client
      expose:
        - "80"
      ports:
        - "80:80"