version: '3'

services:
    api:
      image: irynahalenok/prosimos-api:0.1
      container_name: prosimos-api
      expose:
        - "5000"
      ports:
        - "5000:5000"

    client:
      image: irynahalenok/prosimos-client:0.1
      container_name: prosimos-client
      expose:
        - "80"
      ports:
        - "80:80"