version: '3'

services:
    api:
      image: ${API_IMAGE}
      container_name: prosimos-api
      restart: unless-stopped
      ports:
        - "5000:5000"

    client:
      image: ${CLIENT_IMAGE}
      container_name: prosimos-client
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./certbot/conf:/etc/letsencrypt:ro
        - ./certbot/www:/var/www/certbot:ro
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
    certbot:
      image: certbot/certbot
      container_name: certbot
      restart: unless-stopped
      volumes: 
        - ./certbot/conf:/etc/letsencrypt:rw
        - ./certbot/www:/var/www/certbot:rw
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
